---
label: product
hide_body: true
fields:
- name: id
  type: text
  config:
    required: false
  label: id
  description: Id
- name: name
  type: text
  config:
    required: false
  label: Name
  description: Name
- name: price
  type: text
  config:
    required: false
  label: Price
  description: Price
- name: description
  type: text
  config:
    required: false
  label: Description
  description: Description
- name: image
  type: file
  config:
    maxSize: 250
  label: Image
  description: Image
- name: pruduct_url
  type: text
  config:
    required: false
  label: Pruduct URL
  description: Product URL
